# Account-Mall 系统配置文档
# 作者：吴英涛（Orzice） 1073519986@qq.com
# 仓库地址：https://gitee.com/orzice/account-mall
# 仓库地址：https://github.com/orzice/account-mall

# 应用配置
app:
  # 应用目录 默认. 代表程序允许目录
  app_path: .
  # 程序对外访问的网址
  http_server_url: "http://localhost:9090"
  # 程序监听的端口，如不使用Nginx 则写 80 或 443，否则 请反向代理到 规定端口
  http_port: 9090

# JWT加密验签
jwt:
  # 后台密钥
  secret: "Account-Mall"
  # 前台密钥
  secret_user: "124wdthds345"

# 数据库配置
database:
  # 可支持 mysql  sqlite
  driver: sqlite
  host: localhost
  port: 3306
  dbname: account_mall
  username: account_mall
  password: account_mall
  prefix: am_
  prefix_cmf: cmf_
  charset: utf8mb4
cache:
  # 可支持 file  redis
  type : "file"
  # 缓存根目录 默认. 代表程序允许目录
  file_path: .
redis:
  # 1开启Redis 0关闭Redis
  isOpen: 0
  conn: 127.0.0.1:6379
  dbNum: 0
  password: ""
email:
  # 1开启邮箱服务 0关闭邮箱服务
  isOpen: 0
  serverHost: smtp.163.com
  serverPort: 25
  fromPasswd: 11111
  fromEmail: 111111@163.com
  insecureSkipVerify: true
grpc:
    token: xV0f4c3sRF&Mn5aXPpF6ITIAAMm%CKF8
    ip_list:
      - ip: ::1
      - ip: localhost
      - ip: 127.0.0.1
      - ip: 127.0.0.2